<?xml version="1.0"?>
<package format="3">
  <name>openarm_exoskeleton</name>
  <version>0.0.1</version>
  <description>Exoskeleton teleoperation package for OpenArm.</description>
  <maintainer email="normal@example.com">normal</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-serial</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>