#!/usr/bin/env python3
"""
ROS2 node for replaying predicted/ground-truth trajectories in RViz.

Reads the npz file generated by replay_inference.py and publishes JointState
messages to visualize the robot motion in RViz. Can toggle between predicted
trajectory and ground truth, or show both side by side.

Prerequisites on industrial PC:
  - ROS2 (Humble/Iron) with URDF packages
  - openarm_description package built
  - numpy installed (pip3 install numpy)

Usage:
  # Terminal 1: Launch RViz with robot model (no joint_state_publisher_gui)
  ros2 launch openarm_description display_openarm.launch.py arm_type:=v10 bimanual:=true

  # But first, kill the joint_state_publisher_gui node:
  ros2 node kill /joint_state_publisher_gui

  # Terminal 2: Run this replay node
  python3 rviz_replay.py --file episode_000_replay.npz --mode predicted

  # Or use the companion launch file:
  python3 rviz_replay.py --file episode_000_replay.npz --mode both --rate 15

Modes:
  predicted    - Show only model predictions
  ground_truth - Show only recorded (ground truth) actions
  both         - Alternate between predicted and ground truth every loop
"""

import argparse
import json
import sys
import time

import numpy as np

try:
    import rclpy
    from rclpy.node import Node
    from sensor_msgs.msg import JointState

    HAS_ROS2 = True
except ImportError:
    HAS_ROS2 = False


class TrajectoryReplayNode(Node):
    """ROS2 node that publishes JointState messages from a saved trajectory."""

    def __init__(self, trajectory_file: str, mode: str = "predicted",
                 rate: float = 15.0, loop: bool = True):
        super().__init__("trajectory_replay")

        # Load trajectory data
        data = np.load(trajectory_file, allow_pickle=True)
        self.gt_states = data["gt_states"]
        self.gt_actions = data["gt_actions"]
        self.pred_actions = data["pred_actions"]
        self.processed_indices = data["processed_indices"]
        self.fps = float(data["fps"])
        self.joint_names = json.loads(str(data["joint_names"]))
        self.task_desc = str(data["task_desc"])

        self.mode = mode
        self.loop = loop
        self.frame_idx = 0
        self.current_mode = "predicted" if mode in ("predicted", "both") else "ground_truth"
        self.loop_count = 0

        # Publisher
        self.pub = self.create_publisher(JointState, "/joint_states", 10)

        # Timer
        self.timer = self.create_timer(1.0 / rate, self.timer_callback)

        self.get_logger().info(f"Task: {self.task_desc}")
        self.get_logger().info(f"Mode: {mode}")
        self.get_logger().info(
            f"GT: {len(self.gt_actions)} frames, "
            f"Pred: {len(self.pred_actions)} frames"
        )
        self.get_logger().info(f"Publishing at {rate} Hz")

    def _get_current_trajectory(self) -> np.ndarray:
        """Get the currently active trajectory based on mode."""
        if self.current_mode == "predicted":
            return self.pred_actions
        else:
            return self.gt_actions

    def timer_callback(self):
        trajectory = self._get_current_trajectory()

        if self.frame_idx >= len(trajectory):
            if self.loop:
                self.frame_idx = 0
                self.loop_count += 1

                # In 'both' mode, alternate between predicted and ground_truth
                if self.mode == "both":
                    if self.current_mode == "predicted":
                        self.current_mode = "ground_truth"
                    else:
                        self.current_mode = "predicted"
                    trajectory = self._get_current_trajectory()

                self.get_logger().info(
                    f"Loop {self.loop_count}: showing {self.current_mode} "
                    f"({len(trajectory)} frames)"
                )
            else:
                self.get_logger().info("Replay complete.")
                self.timer.cancel()
                return

        msg = JointState()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.name = self.joint_names
        msg.position = trajectory[self.frame_idx].tolist()

        self.pub.publish(msg)
        self.frame_idx += 1


def replay_without_ros2(trajectory_file: str, mode: str, rate: float, loop: bool):
    """Fallback replay that prints trajectory to stdout (for debugging without ROS2)."""
    data = np.load(trajectory_file, allow_pickle=True)
    joint_names = json.loads(str(data["joint_names"]))
    task_desc = str(data["task_desc"])

    if mode == "predicted":
        trajectory = data["pred_actions"]
        label = "PREDICTED"
    else:
        trajectory = data["gt_actions"]
        label = "GROUND TRUTH"

    print(f"Task: {task_desc}")
    print(f"Mode: {label} ({len(trajectory)} frames)")
    print(f"Joints: {joint_names}")
    print(f"Rate: {rate} Hz\n")

    dt = 1.0 / rate
    idx = 0
    while True:
        if idx >= len(trajectory):
            if loop:
                idx = 0
                print("\n--- Looping ---\n")
            else:
                break

        positions = trajectory[idx]
        # Print condensed: first 4 joints of each arm
        left_str = " ".join(f"{v:+.3f}" for v in positions[:4])
        right_str = " ".join(f"{v:+.3f}" for v in positions[8:12])
        print(f"[{idx:4d}] L:[{left_str} ...] R:[{right_str} ...]")

        idx += 1
        time.sleep(dt)


def main():
    parser = argparse.ArgumentParser(
        description="Replay GR00T predicted trajectories in RViz"
    )
    parser.add_argument("--file", required=True, help="Path to trajectory npz file")
    parser.add_argument("--mode", default="predicted",
                        choices=["predicted", "ground_truth", "both"],
                        help="Which trajectory to visualize")
    parser.add_argument("--rate", type=float, default=15.0,
                        help="Playback rate in Hz (default: match recording FPS)")
    parser.add_argument("--no_loop", action="store_true",
                        help="Play once and stop")
    parser.add_argument("--no_ros2", action="store_true",
                        help="Run without ROS2 (print to stdout)")
    args = parser.parse_args()

    if args.no_ros2 or not HAS_ROS2:
        if not HAS_ROS2:
            print("ROS2 not available, falling back to stdout mode.")
        replay_without_ros2(args.file, args.mode, args.rate, not args.no_loop)
        return

    rclpy.init()
    node = TrajectoryReplayNode(
        trajectory_file=args.file,
        mode=args.mode,
        rate=args.rate,
        loop=not args.no_loop,
    )

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
